=== ahqstore/cli/.ahqstore/schemas/schema_0.16.0-alpha.28.schema.json
{"$schema":"https://json-schema.org/draft/2020-12/schema","title":"IMetadata","type":"object","properties":{"$schema":{"type":"string"},"appDisplayName":{"description":"The name that'll be displayed in the AHQ Store","type":"string"},"appId":{"description":"The ID of the application","type":"string"},"appShortcutName":{"description":"The name of the shortcut of the app","type":"string"},"authorId":{"description":"Unique ID of the author","type":"string"},"install":{"description":"Install options","$ref":"#/$defs/InstallerOptions"},"licenseOrTos":{"description":"License type or Terms of Service Page","type":["string","null"]},"repo":{"description":"The Repository associated","$ref":"#/$defs/ApplicationRepository"},"shortdesc":{"description":"Short description","type":"string"},"site":{"description":"The Site to your app","type":["string","null"]},"usrVersion":{"description":"A version provided by the user, like AHQ Store CLI","type":["string","null"]}},"required":["$schema","appId","appShortcutName","appDisplayName","shortdesc","authorId","install","repo"],"$defs":{"AndBlock":{"type":"array","items":{"$ref":"#/$defs/OrBlock"}},"AndroidPlatform":{"oneOf":[{"type":"object","properties":{"finder":{"$ref":"#/$defs/Finder"},"installType":{"type":"string","const":"universal"},"intent":{"$ref":"#/$defs/FileIntent"}},"required":["installType","finder","intent"]},{"type":"object","properties":{"arm32":{"$ref":"#/$defs/FileIntent"},"arm64":{"$ref":"#/$defs/FileIntent"},"finder":{"$ref":"#/$defs/Finder"},"installType":{"type":"string","const":"split"},"x64":{"$ref":"#/$defs/FileIntent"},"x86":{"$ref":"#/$defs/FileIntent"}},"required":["installType","finder","x64","x86","arm64","arm32"]}]},"ApplicationRepository":{"type":"object","properties":{"author":{"type":"string"},"repository":{"type":"string"},"source":{"$ref":"#/$defs/GitProvider"}},"required":["source","author","repository"]},"DesktopPlatform":{"type":"object","properties":{"finder":{"$ref":"#/$defs/Finder"},"intent":{"$ref":"#/$defs/FileIntent"}},"required":["finder","intent"]},"FileIntent":{"oneOf":[{"type":"object","properties":{"type":{"type":"string","const":"ArtifactZip"}},"required":["type"]},{"type":"object","properties":{"extension":{"type":"string"},"type":{"type":"string","const":"Artifact"}},"required":["type","extension"]},{"description":"🎯 Stable as of v1","type":"object","properties":{"exec":{"type":"string"},"scope":{"$ref":"#/$defs/WindowsInstallScope"},"type":{"type":"string","const":"WindowsZip"}},"required":["type","exec","scope"]},{"description":"🎯 Stable as of v2","type":"object","properties":{"guid":{"description":"This is an optional field that can be useful for applications\nwhose GUID cannot be reliably fetched from the `.msi` file\n\nSome examples include applications like Firefox where the .msi\nfile effectively calls an `.exe` setup, making our GUID search return\ninvalid outcome.\n\nThe GUID entry should have a `ahqstore` key with SZ field that has the appId\nfor verification","type":["string","null"]},"type":{"type":"string","const":"WindowsInstallerMsi"}},"required":["type"]},{"description":"🎯 Stable after v2","type":"object","properties":{"args":{"type":["array","null"],"items":{"type":"string"}},"type":{"type":"string","const":"WindowsInstallerExe"}},"required":["type"]},{"description":"🔬 Planned in AHQ Store NEO","type":"object","properties":{"aumid":{"description":"This is used incase, we are unable to correctly identify required AUMID from the AppxManifest\n\nRecommended to be present","type":["string","null"]},"type":{"type":"string","const":"WindowsUWPMsix"}},"required":["type"]},{"description":"🔬 Planned in AHQ Store NEO","type":"object","properties":{"scope":{"$ref":"#/$defs/WindowsInstallScope"},"type":{"type":"string","const":"WindowsAHQDB"}},"required":["type","scope"]},{"description":"🎯 Stable as of v2","type":"object","properties":{"type":{"type":"string","const":"LinuxAppImage"}},"required":["type"]},{"description":"🔬 Planned in AHQ Store NEO","type":"object","properties":{"min_sdk":{"type":"integer","format":"uint32","minimum":0},"type":{"type":"string","const":"AndroidApkZip"}},"required":["type","min_sdk"]}]},"Finder":{"description":"All the elements of the Finder are case sensitive\n\nThis Finder structure assumes minimal presence of\nartifact differentiators that are required for a smooth\nartifact match.\nIf your project does not have the minimum presence, you\nmight need to reorganize your CI/CD Pipeline!\n\n## Note\nThe structure has been designed to allow robust pattern matching\nwith static information instead of utilizing a runtime scripting\nlanguage","type":"object","properties":{"contains":{"$ref":"#/$defs/AndBlock"},"endsWith":{"$ref":"#/$defs/OrBlock"},"notcontains":{"$ref":"#/$defs/OrBlock"},"startsWith":{"description":"A list of prefixes that the artifact name should start with","$ref":"#/$defs/OrBlock"}},"required":["startsWith","contains","notcontains","endsWith"]},"GitProvider":{"type":"string","enum":["GitHub","GitLab"]},"InstallerOptions":{"type":"object","properties":{"android":{"anyOf":[{"$ref":"#/$defs/AndroidPlatform"},{"type":"null"}]},"linuxArm64":{"anyOf":[{"$ref":"#/$defs/DesktopPlatform"},{"type":"null"}]},"linuxX64":{"anyOf":[{"$ref":"#/$defs/DesktopPlatform"},{"type":"null"}]},"winArm64":{"anyOf":[{"$ref":"#/$defs/DesktopPlatform"},{"type":"null"}]},"winX64":{"anyOf":[{"$ref":"#/$defs/DesktopPlatform"},{"type":"null"}]}}},"OrBlock":{"type":"array","items":{"type":"string"}},"WindowsInstallScope":{"type":"string","enum":["User","Machine","Both"]}}}

=== ahqstore/cli/.ahqstore/config/metadata.json
{
  "$schema": "../schemas/schema_0.16.0-alpha.28.schema.json",
  "appId": "i6xff9HwbxQFXkcyvgghHZub3mLgTLrI8Ocg5r6fhvSlQpxKra5lhid4VWkPiQ8t",
  "appShortcutName": "Watercooler",
  "appDisplayName": "Cool your life - AHQ Watercooler",
  "shortdesc": "A simple water cooling application. Cool with CPU",
  "authorId": "0001",
  "install": {
    "winX64": null,
    "winArm64": null,
    "linuxX64": null,
    "linuxArm64": null,
    "android": null
  },
  "repo": {
    "source": "GitHub",
    "author": "ahqstore",
    "repository": "watercooler"
  },
  "usrVersion": null,
  "site": null,
  "licenseOrTos": null
}
